#!/usr/bin/env bash
# Entrypoint for the OpenHost-packaged ENiGMA½ BBS.
#
# On first run, this script generates a fresh config (using a random
# sysop password it also writes to sysop-password.txt) and seeds the
# writable ENiGMA directories from the build-time templates. On
# subsequent runs, it's a no-op and just execs ENiGMA.
#
# All mutable state lives under OPENHOST_APP_DATA_DIR. The ENiGMA
# install dir (/enigma-bbs) is treated as read-only — we replace its
# runtime-writable subdirs with symlinks into the data dir so ENiGMA
# can write where it expects to while the actual bytes land in the
# container's persistent mount.

set -euo pipefail

BBS_ROOT=${BBS_ROOT:-/enigma-bbs}
BBS_STAGING=${BBS_STAGING:-/enigma-pre}

# OpenHost provides OPENHOST_APP_DATA_DIR when app_data=true in the
# manifest. Fall back to a sensible default for local testing.
DATA_DIR=${OPENHOST_APP_DATA_DIR:-/enigma-data}

echo "[bbs] data dir: ${DATA_DIR}"

mkdir -p "${DATA_DIR}"

# These are the dirs ENiGMA writes to at runtime. We symlink each one
# back into the install tree so the code finds them at their expected
# paths while the bytes actually live under the data dir.
#   config:    config.hjson + (optional) TLS material + SSH host keys
#   db:        SQLite databases (users, messages, file base, stats)
#   logs:      rotating app log
#   filebase:  uploaded + hosted file areas
#   mods:      site-local mod overrides (seeded from staging on first
#              run so upstream examples aren't lost)
#   art:       themes and ANSI art (seeded from staging too)
RUNTIME_DIRS=(config db logs filebase mods art)

for d in "${RUNTIME_DIRS[@]}"; do
    host_path="${DATA_DIR}/${d}"
    mkdir -p "${host_path}"

    # If the in-image subdir already exists (it will for
    # config/mods/art — they're part of the upstream checkout) drop it
    # so the symlink step below can replace it. That's safe because
    # anything worth keeping is in the staging copy we lifted during
    # image build.
    if [ -e "${BBS_ROOT}/${d}" ] && [ ! -L "${BBS_ROOT}/${d}" ]; then
        rm -rf "${BBS_ROOT}/${d}"
    fi
    rm -f "${BBS_ROOT}/${d}"  # if it was already a (possibly stale) symlink
    ln -s "${host_path}" "${BBS_ROOT}/${d}"
done

# ----------------------------------------------------------------------
# First-run seeding
# ----------------------------------------------------------------------

# Determine "first run" by the presence of the main config file. If
# someone deletes it manually to force a re-seed, that's fine — we'll
# rebuild the starter config and they'll get a new random sysop
# password.
CONFIG_FILE="${DATA_DIR}/config/config.hjson"

seed_from_staging() {
    local name=$1
    local src="${BBS_STAGING}/${name}"
    local dst="${DATA_DIR}/${name}"
    if [ -d "${src}" ] && [ -z "$(ls -A "${dst}" 2>/dev/null)" ]; then
        echo "[bbs] seeding ${name} from staging"
        cp -rp "${src}/." "${dst}/"
    fi
}

if [ ! -f "${CONFIG_FILE}" ]; then
    echo "[bbs] first run — generating starter config + sysop password"

    # Seed config/mods/art from the build-time templates so ENiGMA's
    # default themes, default mods, and default config fragments
    # (other than config.hjson itself) are available out of the box.
    for d in config mods art; do
        seed_from_staging "${d}"
    done

    # Generate a random sysop password and stash it where the operator
    # can find it after deploy. We don't print it to stdout because the
    # OpenHost build log is surfaced in the UI and we don't want the
    # password leaked there.
    SYSOP_PASSWORD=$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)
    SYSOP_PASSWORD_FILE="${DATA_DIR}/config/sysop-password.txt"
    umask 077
    cat > "${SYSOP_PASSWORD_FILE}" <<EOF
ENiGMA½ sysop login
-------------------
Username: sysop
Password: ${SYSOP_PASSWORD}

This file was generated on first run. Log in, change the password,
then delete this file. If you lose the password you can either edit
the users database directly or run \`./oputil.js user pw sysop <new>\`
from inside the container.
EOF
    chmod 600 "${SYSOP_PASSWORD_FILE}"
    umask 022

    # Write a minimal config.hjson. We avoid `oputil.js config new`
    # (interactive) and instead emit a small valid config that relies
    # on ENiGMA's built-in defaults for everything unspecified.
    #
    # Ports inside the container: telnet 8888, ssh 8889 (picked high so
    # they don't need extra capabilities). The openhost.toml maps these
    # to low-numbered host ports.
    cat > "${CONFIG_FILE}" <<HJSON
{
    //  ENiGMA 1/2 BBS — generated by openhost-bbs entrypoint.sh
    //  Edit freely; this file is not regenerated on restart.

    general: {
        boardName: "${BBS_BOARD_NAME:-OpenHost BBS}"
        prettyBoardName: "|09Open|15Host |13BBS"
        sysOp: {
            username: "sysop"
            realName: "${BBS_SYSOP_NAME:-Sysop}"
            location: "${BBS_SYSOP_LOCATION:-cyberspace}"
            affiliations: "ENiGMA½ on OpenHost"
            email: "${BBS_SYSOP_EMAIL:-sysop@example.com}"
        }
        description: "${BBS_DESCRIPTION:-A BBS running on OpenHost}"
        website: "${BBS_WEBSITE:-}"
    }

    loginServers: {
        telnet: {
            enabled: true
            port: 8888
        }
        ssh: {
            enabled: true
            port: 8889
            //  A fresh Ed25519 host key is generated on first boot
            //  (see the entrypoint), living under config/security/.
            privateKeyPem: /enigma-bbs/config/security/ssh_host_key.pem
            privateKeyPass: ""
            algorithms: {
                kex:
                    [
                        curve25519-sha256
                        curve25519-sha256@libssh.org
                        ecdh-sha2-nistp256
                        ecdh-sha2-nistp384
                        ecdh-sha2-nistp521
                        diffie-hellman-group-exchange-sha256
                        diffie-hellman-group14-sha256
                        diffie-hellman-group16-sha512
                        diffie-hellman-group18-sha512
                        diffie-hellman-group14-sha1
                    ]
                cipher:
                    [
                        aes128-ctr
                        aes192-ctr
                        aes256-ctr
                        aes128-gcm@openssh.com
                        aes256-gcm@openssh.com
                    ]
                hmac:
                    [
                        hmac-sha2-256-etm@openssh.com
                        hmac-sha2-512-etm@openssh.com
                        hmac-sha1-etm@openssh.com
                        hmac-sha2-256
                        hmac-sha2-512
                        hmac-sha1
                    ]
                compress:
                    [
                        none
                    ]
            }
        }
    }

    contentServers: {
        web: {
            // HTTP enabled on 8080 so the OpenHost router (which
            // terminates TLS externally and proxies http-to-http
            // internally) has a real backend to hit. HTTPS is
            // disabled here — certificate provisioning is the
            // router's job, not ENiGMA's.
            http: {
                enabled: true
                port: 8080
            }
            https: {
                enabled: false
            }
        }
    }

    paths: {
        //  Pins runtime paths to the locations the entrypoint
        //  symlinks. Useful if someone moves the install dir.
        config: /enigma-bbs/config/
        security: /enigma-bbs/config/security/
        mods: /enigma-bbs/mods/
        db: /enigma-bbs/db/
        modsDb: /enigma-bbs/db/mods/
        logs: /enigma-bbs/logs/
        fileBase: /enigma-bbs/filebase/
    }
}
HJSON
    chmod 644 "${CONFIG_FILE}"

    # Generate an Ed25519 SSH host key so ENiGMA's SSH server has an
    # identity on first boot. We use PEM format (``-m pem``) because
    # the node-ssh library ENiGMA uses can't parse the newer OpenSSH
    # format that ssh-keygen emits by default.
    mkdir -p "${DATA_DIR}/config/security"
    if [ ! -f "${DATA_DIR}/config/security/ssh_host_key.pem" ]; then
        echo "[bbs] generating SSH host key"
        ssh-keygen -q -t ed25519 -N "" -m pem \
            -f "${DATA_DIR}/config/security/ssh_host_key.pem" \
            -C "openhost-bbs-$(date +%Y%m%d)"
        # ssh-keygen writes a .pub next to it; ENiGMA doesn't need it
        # but we leave it in place for operators who want to verify.
        chmod 600 "${DATA_DIR}/config/security/ssh_host_key.pem"
    fi

    # Seed the users table with a sysop entry at the generated
    # password. oputil.js user add is non-interactive (takes --password
    # / --real-name flags) and sets up the row directly in the sqlite
    # DB that config/paths points at.
    echo "[bbs] creating sysop user"
    if ! node /enigma-bbs/oputil.js user add sysop \
        --password "${SYSOP_PASSWORD}" \
        --real-name "${BBS_SYSOP_NAME:-Sysop}" \
        2>&1 | tee -a "${DATA_DIR}/logs/sysop-bootstrap.log"; then
        echo "[bbs] WARNING: sysop user creation failed — you can retry with:" >&2
        echo "[bbs]   podman exec <container> node oputil.js user add sysop --password ... --real-name ..." >&2
    fi

    echo "[bbs] first-run setup done."
    echo "[bbs] sysop password at: ${SYSOP_PASSWORD_FILE}"
else
    echo "[bbs] existing config found, starting ENiGMA"
fi

# Hand off to the command (default: node main.js). exec so signals
# reach the Node process directly — no pm2, no bash between us and it.
exec "$@"
